[tool.poetry]
name = "crypto-rank-tracker"
version = "0.1.7"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.10"
aiohttp = "^3.12.13"
google-cloud-storage = "^3.1.1"
aiofiles = "^24.1.0"
tenacity = "^9.1.2"
pydantic = "^2.11.7"
numpy = ">=2.0,<2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
